create table if not exists public.company_settings (
  id bigint primary key,
  name text not null,
  currency text not null default 'BRL',
  updated_at timestamptz not null default now()
);

create table if not exists public.app_users (
  id bigint generated by default as identity primary key,
  name text not null,
  username text not null unique,
  password text not null,
  role text not null default 'user' check (role in ('admin', 'user')),
  created_at timestamptz not null default now()
);

create table if not exists public.finance_categories (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('revenue', 'expense')),
  name text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.finance_transactions (
  id bigint primary key,
  type text not null check (type in ('revenue', 'expense')),
  date date not null,
  category text not null,
  description text not null,
  amount numeric(14,2) not null check (amount >= 0),
  user_name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.finance_goals (
  id bigint primary key,
  month text not null,
  title text not null,
  type text not null check (type in ('revenue', 'expenseLimit', 'balance')),
  value numeric(14,2) not null check (value >= 0),
  created_at timestamptz not null default now()
);

insert into public.company_settings (id, name, currency)
values (1, 'NOME DA SUA EMPRESA', 'BRL')
on conflict (id) do update
set name = excluded.name,
    currency = excluded.currency,
    updated_at = now();

insert into public.app_users (name, username, password, role)
values
  ('Administrador', 'admin', '123456', 'admin'),
  ('Usuário Padrão', 'usuario', '123456', 'user')
on conflict (username) do nothing;

insert into public.finance_categories (type, name, sort_order)
values
  ('revenue', 'Venda', 1),
  ('revenue', 'Serviços', 2),
  ('revenue', 'Consultoria', 3),
  ('revenue', 'Contrato', 4),
  ('revenue', 'Outros', 5),
  ('expense', 'Equipamentos', 1),
  ('expense', 'Marketing', 2),
  ('expense', 'Impostos', 3),
  ('expense', 'Salários', 4),
  ('expense', 'Transporte', 5),
  ('expense', 'Operacional', 6),
  ('expense', 'Outros', 7)
on conflict do nothing;
